setlocal colorcolumn=80
setlocal formatoptions+=t
setlocal textwidth=80
setlocal shiftwidth=2
setlocal softtabstop=2
setlocal tabstop=2
let b:autoformat_autoindent = 0
let b:autoformat_retab = 0
let b:autoformat_remove_trailing_spaces = 0
