custom-commands:
  - name: mine
    help: display issues assigned to me
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
        {{jira}} list --query "status IN ('To Do', 'In Progress', 'In Review') AND Assignee=currentuser() AND project = $JIRA_PROJECT ORDER BY priority asc, created"
      else
        {{jira}} list --query "status IN ('To Do', 'In Progress', 'In Review') AND assignee=currentuser() ORDER BY priority asc, created"
      fi

  - name: sprint
    help: display issues for active sprint
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
        {{jira}} list --query "sprint IN openSprints() AND type != epic AND resolution = unresolved AND project=$JIRA_PROJECT ORDER BY rank asc, created"
      else
        echo "project configuration missing from .jira.d/config.yml"
      fi

  - name: env
    help: print the JIRA environment variables available to custom commands
    script: |
      env | grep JIRA

  - name: project-name
    help: print the name of the configured project
    script: "echo $JIRA_PROJECT"
